//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextProcessor.DatabaseModel.EF_Model
{
    
    public partial class DICTIONARY
    {
        public int? ID { get; set; }
        public string WORD { get; set; }
        public decimal FREQUENCY { get; set; }
    }
}
