//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextProcessor.DatabaseModel.EF_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TextDictionaryDatabaseEntities : DbContext
    {
        public TextDictionaryDatabaseEntities()
            : base("name=TextDictionaryDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DICTIONARY> DICTIONARY { get; set; }
        public virtual DbSet<WORD2FREQUENCY> WORD2FREQUENCY { get; set; }
    
        public virtual int INS_WORD_FREQUENCY(string word, Nullable<decimal> frequency)
        {
            var wordParameter = word != null ?
                new ObjectParameter("word", word) :
                new ObjectParameter("word", typeof(string));
    
            var frequencyParameter = frequency.HasValue ?
                new ObjectParameter("frequency", frequency) :
                new ObjectParameter("frequency", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INS_WORD_FREQUENCY", wordParameter, frequencyParameter);
        }
    
        public virtual ObjectResult<string> SEL_WORD_TOP_FREQUENCY(string word)
        {
            var wordParameter = word != null ?
                new ObjectParameter("word", word) :
                new ObjectParameter("word", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SEL_WORD_TOP_FREQUENCY", wordParameter);
        }
    
        public virtual int DeleteDictionaryFromDatabase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteDictionaryFromDatabase");
        }
    }
}
