//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextProcessor.DatabaseModel.EF_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TextDictionaryDatabaseEntities : DbContext
    {
        public TextDictionaryDatabaseEntities()
            : base("name=TextDictionaryDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DICTIONARY> DICTIONARY { get; set; }
    
        public virtual ObjectResult<string> GET_WORD_FREQUENCY(string substr_word)
        {
            var substr_wordParameter = substr_word != null ?
                new ObjectParameter("substr_word", substr_word) :
                new ObjectParameter("substr_word", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("GET_WORD_FREQUENCY", substr_wordParameter);
        }
    }
}
