//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextProcessor.DatabaseModel.EF_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORD2FREQUENCY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORD2FREQUENCY()
        {
            this.DICTIONARY = new HashSet<DICTIONARY>();
        }
    
        public long WORD2FREQUENCY_ID { get; set; }
        public decimal FREQUENCY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DICTIONARY> DICTIONARY { get; set; }
    }
}
